spring:
  datasource:
    url: jdbc:h2:./taskManager;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
logging:
  level:
    web: "DEBUG"


